trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Install a specific version to bypass the '2.100' bug
- task: JFrogToolsInstaller@1
  inputs:
    jfrogCliVersion: '2.99.1' 

# 2. Authenticate using the Service Connection you just created
- task: JfrogCliV2@1
  displayName: 'JFrog OIDC Auth'
  inputs:
    # Use the EXACT name you typed in the "Service Connection Name" box earlier
    jfrogPlatformConnection: 'JFrog-OIDC-Conn' 
    command: 'jf rt ping'

# 3. Test the upload
- task: JfrogCliV2@1
  displayName: 'Replicate and Test Upload'
  inputs:
    jfrogPlatformConnection: 'JFrog-OIDC-Conn'
    command: 'jf rt upload "test.txt" "czm-aden-generic-local/"'