trigger:
- main

pool:
  name: Default

variables:
  CONNECTION_NAME: 'jfrog-oidc-azure1'

steps:
- checkout: self

- script: |
    echo "Downloading JFrog CLI..."
    curl -fL https://getcli.jfrog.io/v2-jf | sh
    chmod +x jf
    ./jf --version
    # This adds the current folder to the PATH so 'jf' works in the next tasks
    echo "##vso[task.prependpath]$(pwd)"
  displayName: 'Install JFrog CLI'

- task: JfrogCliV2@1
  displayName: 'Authenticate with JFrog OIDC'
  inputs:
    jfrogPlatformConnection: $(CONNECTION_NAME)
    command: 'jf rt ping'

- script: |
    echo "OIDC Success - $(Build.BuildId)" > success.txt
    jf rt upload "success.txt" "example-repo-local/azure-oidc/"
  displayName: 'Test Upload'