trigger:
- main

pool:
  name: Default # Keep that Mac terminal running!

variables:
  CONNECTION_NAME: 'jfrog-oidc-azure1' # Matches your screenshot

jobs:
- job: JFROG_CLEAN_START
  steps:
    - checkout: self

    - script: |
        curl -fL https://getcli.jfrog.io/v2-jf | sh
        chmod +x jf
        sudo mv jf /usr/local/bin/
        jf --version
      displayName: 'Install JFrog CLI'

    - task: JfrogCliV2@1
      displayName: 'OIDC Auth'
      inputs:
        jfrogPlatformConnection: $(CONNECTION_NAME)
        command: 'jf rt ping'